version: '3'
services:
    nginx:
        build:
            context: ./
            dockerfile: docker/development/nginx/Dockerfile
        volumes:
            - ./:/var/www
        ports:
            - "86:80"
        depends_on:
            - php-fpm

    php-fpm:
        build:
            context: ./
            dockerfile: docker/development/php-fpm/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - mysql

    php-cli:
        build:
            context: ./
            dockerfile: docker/development/php-cli/Dockerfile
        volumes:
            - ./:/var/www
            - composer:/root/.composer/cache
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        volumes:
            - mysql-volume:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=123456"
            - "MYSQL_USER=db_user"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=db_name"
        ports:
            - "33062:3306"

volumes:
    composer:
    mysql-volume:

